- name: Download k3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0700'

- name: Install k3s agent
  command: /tmp/k3s_install.sh
  environment:
    K3S_URL: "https://{{ k3s_master_ip }}:6443"
    K3S_TOKEN: "{{ k3s_node_token }}"
  become: yes
