- name: Download k3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0700'
  become: yes

- name: Install k3s master
  command: /tmp/k3s_install.sh
  environment:
    INSTALL_K3S_EXEC: "server"
  become: yes

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  become: yes

- name: Read node-token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  become: yes

- name: Store node-token
  set_fact:
    k3s_node_token: "{{ node_token['content'] | b64decode | regex_replace('\n', '') }}"

- name: Get k3s master IP
  set_fact:
    k3s_master_ip: "{{ ansible_default_ipv4.address }}"

- name: Register k3s master IP
  add_host:
    name: "k3s_master"
    k3s_master_ip: "{{ k3s_master_ip }}"

- name: Create kubectl group
  group:
    name: kubectl
    state: present
  become: yes

- name: Add ubuntu user to kubectl group
  user:
    name: ubuntu
    groups: kubectl
    append: yes
  become: yes

- name: Set permissions for kubeconfig
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: root
    group: kubectl
    mode: '0640'
  become: yes
